# Generated by Django 5.1.4 on 2024-12-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task Name')),
                ('url', models.URLField(verbose_name='Task URL')),
                ('is_active', models.BooleanField(default=True)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(verbose_name='Description')),
                ('task_type', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('other', 'Other')], default='other', max_length=10, verbose_name='Task Type')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram User ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('lvl_status', models.IntegerField(default=1, verbose_name='User Deposit Level')),
                ('balance', models.IntegerField(default=0, verbose_name='User balance')),
                ('depozite', models.IntegerField(default=0, verbose_name='User Deposit price')),
                ('passport_pic', models.FilePathField(verbose_name='User passport photo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('amount_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.telegramuser')),
            ],
        ),
    ]
