# Generated by Django 5.1.4 on 2024-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='passport_pic',
            field=models.ImageField(upload_to='files/', verbose_name='User passport photo'),
        ),
    ]
