# Generated by Django 5.1.4 on 2024-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_alter_telegramuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='withdraw',
            field=models.IntegerField(default=0, verbose_name='Money withdraw'),
        ),
    ]
