# Generated by Django 5.1.4 on 2024-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_telegramuser_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='reff',
            field=models.IntegerField(default=0, verbose_name='User referal count'),
        ),
    ]
