# Generated by Django 5.1.4 on 2024-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_telegramuser_reff'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.TextField(blank=True, null=True, verbose_name='Bot qo‘llanmasi')),
                ('mandatory_channels', models.PositiveIntegerField(default=0, verbose_name='Majburiy kanallar soni')),
            ],
            options={
                'verbose_name': 'Bot statistikasi',
                'verbose_name_plural': 'Bot statistikasi',
            },
        ),
        migrations.CreateModel(
            name='MandatoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='Kanal/Guruh ID')),
                ('channel_name', models.CharField(max_length=255, verbose_name='Kanal/Guruh nomi')),
                ('channel_type', models.CharField(choices=[('channel', 'Kanal'), ('group', 'Guruh')], max_length=10, verbose_name='Kanal turi')),
                ('channel_url', models.URLField(blank=True, null=True, verbose_name='Kanal/Guruh URL manzili')),
            ],
            options={
                'verbose_name': 'Majburiy kanal/guruh',
                'verbose_name_plural': 'Majburiy kanallar/guruhlar',
            },
        ),
    ]
