# Generated by Django 5.1.4 on 2024-12-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0008_channel_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
