# Generated by Django 5.1.4 on 2024-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0009_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.TextField(verbose_name='Task URL'),
        ),
    ]
