# Generated by Django 5.1.4 on 2024-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_alter_task_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Task Url'),
        ),
    ]
