# Generated by Django 5.1.4 on 2024-12-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0012_mandatorychannel_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botstats',
            name='mandatory_channels',
        ),
        migrations.AddField(
            model_name='botstats',
            name='referral_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Referal narxi (so‘m)'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to='Bot.telegramuser', verbose_name='Taklif qilingan foydalanuvchi')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='Bot.telegramuser', verbose_name='Taklif qiluvchi')),
            ],
            options={
                'verbose_name': 'Referal',
                'verbose_name_plural': 'Referallar',
            },
        ),
    ]
