# Generated by Django 5.1.4 on 2024-12-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0013_remove_botstats_mandatory_channels_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referral'},
        ),
        migrations.RemoveField(
            model_name='botstats',
            name='referral_price',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Referral narxi'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Taklif qilingan sana'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='Bot.telegramuser', verbose_name='Taklif qilingan foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_users', to='Bot.telegramuser', verbose_name='Taklif qiluvchi foydalanuvchi'),
        ),
    ]
