# Generated by Django 5.1.4 on 2024-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0015_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='message_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Xabar ID'),
        ),
        migrations.AlterField(
            model_name='mandatorychannel',
            name='purpose',
            field=models.CharField(choices=[('payments', 'To‘lovlar uchun'), ('check_task', 'Vazifalarni tekshirish uchun'), ('user_verification', 'Foydalanuvchilarni tasdiqlash uchun'), ('for_appeal', 'Murojaatlarni tekshirish uchun'), ('admin_channel', 'Admin kanali'), ('advertising_channel', 'Reklama kanali'), ('other', 'Boshqa maqsadlar')], default='other', max_length=20, verbose_name='Kanal/Guruh maqsadi'),
        ),
    ]
