# Generated by Django 5.1.4 on 2024-12-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0016_usermessage_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='passport_pic',
        ),
        migrations.AlterField(
            model_name='mandatorychannel',
            name='purpose',
            field=models.CharField(choices=[('payments', 'To‘lovlar uchun'), ('check_task', 'Vazifalarni tekshirish uchun'), ('user_verification', 'Foydalanuvchilarni tasdiqlash uchun'), ('admin_channel', 'Admin kanali'), ('advertising_channel', 'Reklama kanali'), ('other', 'Boshqa maqsadlar')], default='other', max_length=20, verbose_name='Kanal/Guruh maqsadi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='status',
            field=models.CharField(choices=[('user', 'User'), ('main_admin', 'Bosh Admin'), ('admin_request', 'Murojaat Admin'), ('payment_admin', "To'lo'v Admin"), ('deposit_admin', 'Depozit Admin')], default='user', max_length=15, verbose_name='User Status'),
        ),
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('passport_series', models.CharField(help_text='Format: AA1234567', max_length=9, unique=True, verbose_name='Passport Series')),
                ('passport_image', models.ImageField(upload_to='passport_images/', verbose_name='Passport Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_info', to='Bot.telegramuser', verbose_name='Related User')),
            ],
            options={
                'verbose_name': 'Passport Information',
                'verbose_name_plural': 'Passport Informations',
            },
        ),
    ]
