# Generated by Django 5.1.4 on 2024-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0017_remove_telegramuser_passport_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
