# Generated by Django 5.1.4 on 2024-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0018_alter_telegramuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.IntegerField(verbose_name='Task reward'),
        ),
    ]
