# Generated by Django 5.1.4 on 2024-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0021_botstats_deposit_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='task_completed_count',
            field=models.IntegerField(default=0, verbose_name='Task Completed Count'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='User Balance'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='depozite',
            field=models.IntegerField(default=0, verbose_name='User Deposit Price'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='reff',
            field=models.IntegerField(default=0, verbose_name='User Referral Count'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='withdraw',
            field=models.IntegerField(default=0, verbose_name='Money Withdraw'),
        ),
    ]
