# Generated by Django 5.1.4 on 2024-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0022_telegramuser_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='task_completed_count',
            field=models.CharField(default=0, max_length=10, verbose_name='Task Completed Count'),
        ),
    ]
