# Generated by Django 5.1.4 on 2024-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0023_alter_telegramuser_task_completed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='lvl_status',
        ),
        migrations.AddField(
            model_name='botstats',
            name='bonus_money',
            field=models.IntegerField(default=5000, verbose_name="Userni birinchi botga kirganda sovg'a puli"),
        ),
        migrations.AddField(
            model_name='botstats',
            name='daily_limit',
            field=models.IntegerField(default=0, verbose_name='Userlarning kunlik vazifa bajarish limiti'),
        ),
    ]
